# Basic
title: Zhaopeng Blog
subtitle: A blog for strong
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Welcome to My World</a>
description: I work on software project in China . Maybe I can work on the world if have chance.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://www.baiducom"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Corperation, description: My arbor, url: 'www.yundijie.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: Zhaopeng-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: ypeanng
    github: ypeanng
    twitter: ypeanng
    gplus: 107108267983477358170
    mail: ypeanng@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
